version: "3.1"
services:
    
  database:
      image: postgres
      container_name: "delivery-center-operations"
      restart: always
      environment:
          - POSTGRES_USER=deliverycenter
          - POSTGRES_PASSWORD=post2021
          - POSTGRES_DB=operations
      ports:
          - "5432:5432"
      volumes:
          - ./database:/var/lib/postgresql/data/ 

  datawarehouse:
      image: postgres
      container_name: "delivery-center-analytics"
      restart: always
      environment:
          - POSTGRES_USER=deliverycenter
          - POSTGRES_PASSWORD=post2021
          - POSTGRES_DB=analytics
      ports:
          - "5433:5432"
      volumes:
          - ./datawarehouse:/var/lib/postgresql/data/ 
  
  # spark:
  #   image: docker.io/bitnami/spark:3
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   ports:
  #     - '8080:8080'
  # spark-worker-1:
  #   image: docker.io/bitnami/spark:3
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark:7077
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  # spark-worker-2:
  #   image: docker.io/bitnami/spark:3
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark:7077
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no

  metabase:
          image: metabase/metabase
          container_name: "metabase_dc"
          ports:
              - "3000:3000"
          links: 
              - datawarehouse
